Updated config.go - added defaults config option
alec-pinson/ip-whitelister pull request #57
Opened 2022-12-22 14:51 UTC by JNickson

Allows for subscription_id and resource_group to have a default value to fall back on per config file for all resources in that file.

2022-12-22 14:57 UTC, alec-pinson commented
Haven't looked properly yet because it's hard to read on my phone but might be worth adding an app3.yaml in resources with an example of how to use what you added.

2022-12-22 15:32 UTC, alec-pinson commented on config.go
> +	Defaults       []string `yaml:"defaults"`
Think you added this and don't actually use it ?

2022-12-22 15:33 UTC, alec-pinson commented on config.go
> +	Defaults    []Defaults              `yaml:"defaults"`
Don't think there's any need for this to be an array of Defaults?

2022-12-22 15:33 UTC, alec-pinson commented on config.go
> +	Defaults    []Defaults              `yaml:"defaults"`
```suggestion
	Defaults    Defaults              `yaml:"defaults"`
```

2022-12-22 15:34 UTC, alec-pinson commented on config.go
> +				subId = config.Defaults[0].SubscriptionId
```suggestion
				subId = config.Defaults.SubscriptionId
```
Don't think this needs to be an array

2022-12-22 15:34 UTC, alec-pinson commented on config.go
> +				rg = config.Defaults[0].ResourceGroup
```suggestion
				rg = config.Defaults.ResourceGroup
```
Don't think this needs to be an array

2022-12-22 15:34 UTC, alec-pinson commented on config/config.yaml
> +    resource_group: notreal-default-rg
```suggestion
defaults:
  subscription_id: notreal-default-subscription
  resource_group: notreal-default-rg
```
Don't think this needs to be an array/list/slince whatever it is :D

2022-12-22 15:35 UTC, alec-pinson commented on config/resources/app2.yaml
> +    resource_group: notreal-default-rg
```suggestion
  subscription_id: notreal-default-subscription
  resource_group: notreal-default-rg
```
Don't think this needs to be an array/list/slince whatever it is :D

2022-12-22 15:35 UTC, alec-pinson commented on config/resources/app3.yaml
> +    resource_group: notreal-default-rg
```suggestion
  subscription_id: notreal-default-subscription
  resource_group: notreal-default-rg
```
Don't think this needs to be an array/list/slince whatever it is :D

2022-12-22 15:35 UTC, alec-pinson commented on config/resources/app3.yaml
> +
```suggestion

```
Fix line end

2022-12-22 16:39 UTC, JNickson commented on config.go
> +	Defaults    []Defaults              `yaml:"defaults"`
ah yeah okay that works the same lol

2022-12-22 16:40 UTC, JNickson commented on config.go
> +	Defaults       []string `yaml:"defaults"`
yeah that was a mistake was mean't to remove that

2022-12-23 08:57 UTC, alec-pinson requested changes
Just a lil cleanup on the if else :)

2022-12-23 08:57 UTC, alec-pinson commented on config.go
> +			} else if resource.SubscriptionId != "" {
```suggestion
			} else {
```

2022-12-23 08:57 UTC, alec-pinson commented on config.go
> +			} else if resource.ResourceGroup != "" {
```suggestion
			} else {
```

2022-12-24 11:45 UTC, merged